baseURL = "/"
languageCode = "en-us"
title = "Freedom Security Solutions"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = false     # show / hide the contaxt box on the homepage
    show_contact_form = true     # show / hide the contact form on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/freedom-security-solutions.png"
    mobile_height = "96px"
    alt = "Freedom Security Solutions"

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Freedom Security Solutions © 2022. All Rights Reserved'
    show_contact_box = true     # show / hide the contaxt box on the footer
    show_services_button = false # show / hide the "view all services" button

[menu]
  # Main Menu
  [[menu.main]]
    name = "About Us"
    url = "/about-us/"
    weight = 1

  [[menu.main]]
    name = "Work With Us"
    url = "/work-with-us/"
    weight = 2

  [[menu.main]]
    name = "Services"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Contact Us"
    url = "/contact-us/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Contact Us"
    url = "/contact-us/"
    weight = 2